{==============================================================================
                         _          
 __ ___  _ ___ _ _  __ _(_)_ _  ___™ 
 \ \ / || / -_) ' \/ _` | | ' \/ -_)
 /_\_\\_, \___|_||_\__, |_|_||_\___|
      |__/         |___/            

 Copyright © 2020-21 tinyBigGAMES™ LLC
 All rights reserved.

 website: https://tinybiggames.com
 email  : support@tinybiggames.com
 
============================================================================== }

{$WARN SYMBOL_DEPRECATED OFF}
{$WARN SYMBOL_PLATFORM OFF}

{$WARN UNIT_PLATFORM OFF}
{$WARN UNIT_DEPRECATED OFF}

{$MINENUMSIZE 4}
{$ALIGN ON}

{$Z4}
{$A8}

{$INLINE AUTO}


